name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up MSVC
        uses: microsoft/setup-msbuild@v1

      - name: Install Dependencies
        run: |
          # Assuming you're using vcpkg for dependency management
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.bat
          ./vcpkg/vcpkg install zlib

      - name: Build Project
        run: |
          pushd "D:\a\StreamFX-Public\StreamFX-Public"
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build . --config RelWithDebInfo

      - name: Run Tests
        run: |
          pushd "D:\a\StreamFX-Public\StreamFX-Public\build"
          ctest --output-on-failure

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: D:\a\StreamFX-Public\StreamFX-Public\build

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get install -y zlib1g-dev
          
      - name: Build Project
        run: |
          mkdir build
          cd build
          cmake .. 
          make

      - name: Run Tests
        run: |
          cd build
          make test

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build
